[[section-introduction-and-goals]]
== Introduction and Goals
LoMap consists on an application where you can access to a map and add markers, routes and share it with your friends. 

It's being developed by software architecture students during 2023. 

It follows SOLID principles, ensuring privacy and availability of the data.

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview
The application shows a map of a city or place. Each user is able to modify it's map to customize and personalized. The users can personalize it's maps by adding 
markers, which can define bars, restaurants, sights, or points of interests from the city. This markers are stored, so that each user, by login in, can access to his personal map.

This storage will be handled according to the SOLID principles.

It's also possible to personalize a map of every city, since this app is not limited by a region or country, and can be accessed from anywhere.

.Requirements: 
* Add different categories for each location
* See the locations in a map in form of markers
* Interact with markers adding photos, reviews or comments.
* Manage a list of friends.
* Manage the information that is shared with your friends.
* See the locations created by friends.
* Filter the locations of the map by categories.

There are also some optional features which, by today, are still not defined whether if they'll be done or not. This can be seen in the https://arquisoft.github.io/course2223/labAssignmentDescription.html#OPTIONAL[Lab assingmnent]

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals


[options="header", cols="1,1"]
|===
| Goal | Description

| Security | Each user should access to it's pod and it can not be accessed by other user. User can modify their access data.

| Performance | The application should be able to give short response time when users are interacting with it. 

| Availability | The personal data from the pods can be accessed at any time.

| Usability | The application should be easy to use. This can be achieved by using different technices such as familiarity, learnability, etc.

| Portability | The application must work regarding the device, since it will be developed as a web application.

| Testability | There must be tests for the application in order to check it's correct behavior.

|===

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Description|Expectations
| Developers | People that are implementing and mantaining the app | A good documentation and well commented code, avoiding repetitions and with a good use of patterns, in order to be easy to modify or extend.
| Professors | In charge of the subject. | An application fullfilling the expectations, that can be qualified. They can also give feedback and help to the developers.
| Users | Interact with the application | A good, easy to use application, that responds well to their inputs and adds value to them, while keeping their data secure.
|===