[[section-solution-strategy]]
== Solution Strategy
In this section some strategies decided by the team will be stated. This strategies might grow whith the development of the application.

.Technologies
* Google Maps API: This API allows us to build the map which whill be needed to the development of the application. This api has been chosen because it's reliable and has been used by some of our team members before.
* MySQL: This DB provides a robust way to store the data that won't be stored at each user's pod. It has been chosen because it's a simple but powerfull database, well-known and we have worked previously with it.
* TypeScript: This language, that comes from JavaScript, provides a powerfull language to program the client part of our application. It provides a good documentation and some tools that JavaScript does not provide that makes it more powerfull.
* Arc42: This template allows our documentation to be organized, and well specified, and also gives us a path to follow and simplify the process.
* Solid: In order to store each user's pod and keep the data decentralized. It offers good security and performance.
* React: A JavaScript library for user interfaces. It is widely used in the industry because it helps building rich user interfaces in a simple way, and allows flexibility and is easy to mantain.
* NodeJS: Another JavaScript library for the server layer that provides the tools to implement the application. It also supports different types of databases and has a large and active community, that might comme in handy when we have questions.
* Docker: In order to deploy the application. It conteinerizes it for automated deployment.

.Design
* Adapter pattern for using the API that might be needed, for example the google maps API.

.Organizational
* Good, up to date documentation, in order to make the development easy to follow.
* Github for communication of the team members and merging the code, by using branches, issues and wikis.
* Weekly meetings, where we take and discuss decisions and review each week's tasks.


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
