[[section-solution-strategy]]
== Solution Strategy
In this section strategies decided by the team will be stated.

=== Technologies
* *TypeScript*. This language, that comes from JavaScript, provides a powerful language to program the client part of our application. It provides a good documentation and some tools that JavaScript does not provide that makes it more powerfull.
* *Arc42*. This template allows our documentation to be organized, and well specified, and also gives us a path to follow and simplify the process.
* *Google Maps API*. This API allows us to build the map which will be needed to the development of the application. This api has been chosen because it's reliable and has been used by some of our team members before. Achieves usability, deployment and good user experience.
* *Solid*. In order to store each user's pod and keep the data decentralized. Achieves security and privacy.
* *React*. A JavaScript library for user interfaces. It is widely used in the industry because it helps building rich user interfaces in a simple way, and allows flexibility and is easy to mantain.
* *NodeJS*. Another JavaScript library for the server layer that provides the tools to implement the application. It also supports different types of databases and has a large and active community, that might comme in handy when we have questions.
* *Docker*. In order to deploy the application. It containerizes it for automated deployment. Achieves portability.
* *Chakra UI*. Component and modular library to create HTML customized and themeable components. Achieves usability.
* *Inrupt Solid APIs*. Set of libraries developed by inrupt to manage and control the information and features in the Solid pod.
* *RDF*. Semantic web standard used to describe and model information for web resources, in this case, used to store information in the Solid pod.
* *Turtle*. RDF syntax that allows an RDF graph to be completely written in a compact and natural text form, with abbreviations for common usage patterns and datatypes
* *Cucumber*. Testing tool that supports Behavior Driven Development (BDD). Achieves Testability
* *Gatling*. Load testing tool. Achieves Testability.
* *End-to-end testing*. Methodology to test from the end user's experience by simulating the real user scenario and validating the system and its components for integration and data integrity. Achieves Test Coverage

=== Design
* *Serverless application*. This application won't rely on a server nor have a database.
* *Client-side component*. The code resides in the browser, receives requests and presents the user with the required information.
* *Pod architecture*. Data stored in pods will be divided in different paths and subfolders to achieve privacy and security.

=== Organizational
* *Up to date documentation*. In order to make the development easy to follow.
* *Github*. Communication of the team members and merging the code, by using branches, issues and wikis.
* *Weekly meetings*. Discuss decisions and review each week's tasks.


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
