[[section-runtime-view]]
== Runtime View

In this section some use cases will be explained.

=== Login to Solid

When the user enters the application, a dialog is displayed for login, where he gets redirected to the pod provider's login.

[plantuml,"Login to Solid",png]
----
@startuml
header LoMap-en2a

title Login to Solid

database PodProvider

User -> Application: select pod provider
User -> Application: click login button
Application-> PodProvider: redirect login
User -> PodProvider: login to solid
Application -> PodProvider: useSession()
Application -> Application: setLogged(true)

@enduml
----

=== Add location to the user's map

To add a location, the user clicks on the bottom-right corner icon. Once it's selected, the user clicks on the desired place in the map.
A window appears where he writes the information. Once it's written, he adds the location, and the application saves it at the user's pod.

[plantuml,"Addition of a location",png]
----
@startuml

header LoMap-en2a

title Addition of a location

database PodProvider

User -> Application: select add location
Application -> Application: setAddLocationMode()
User -> Map: click on the map
Map -> Application: setClickedCoordinates(lat,lon)
Map -> Application: setAddLocationMode(false)
Map -> Application: setSelectedView(AddLocationForm)
User -> AddLocationForm: write fields of the location
User -> AddLocationForm: click add location
AddLocationForm -> AddLocationForm: addLocation(location)
AddLocationForm -> Application: setSelectedView(Map)
AddLocationForm -> Application: setClickedCoordinates(lat,lon)
AddLocationForm -> SolidManagement: createLocation(webId,location)
SolidManagement -> PodProvider: createLocation(webId, location)
AddLocationForm -> SolidManagement: loadUserLocations()
PodProvider -> SolidManagement: Location[]
SolidManagement -> Application: list of locations
Application -> Application: setOwnLocations(locations)
Application -> Map: generates markers
@enduml
----

=== Remove location from user's map

To remove a location, the user clicks on the marker of the map. The marker will display the details of a location. There, he can click the delete button,
and the location will be removed.

[plantuml,"Remove location from map",png]
-----
@startuml

header LoMap-en2a

title Remove a location

database PodProvider
actor User

User -> Map : click on the marker
Map -> Application: setSelectedLocation(location)
Map -> Application: setSelectedView(LocationDetail)
User -> LocationInfo: click delete button
User -> DeleteAlertDialog: wants to delete
DeleteAlertDialog -> SolidManagement: deleteLocation(webId, location)
SolidManagement -> PodProvider: deleteLocation(webId, location)
DeleteAlertDialog -> Application: setSelectedView(Map)
DeleteAlertDialog -> SolidManagement: loadUserLocations()
SolidManagement -> PodProvider: gets user locations
PodProvider -> SolidManagement: list of locations
SolidManagement -> Application: list of locations
Application -> Application: setOwnLocations(locations)
Application -> Map: generates markers

@enduml
-----

=== Add a friend
With lomap, users can add friends directly to their solid account. The user clicks the friends button in the menu, and inputs the webId of the friend.
Then, the friend is added to it's solid account.

[plantuml,"Add a friend",png]
----
@startuml

header LoMap-en2a

title Add a friend

database PodProvider
actor User

User -> Application: click friends button
Application -> Application: setSelectedView(friends)
Friends -> SolidManagement: loadFriends(webId)
SolidManagement -> PodProvider: loadFriends()
PodProvider -> PodProvider: gets user's pictures and names
PodProvider -> SolidManagement: List of friends
Friends -> Friends: shows friends
User -> Friends: writes webId of the friend
User -> Friends: clicks add button
Friends -> SolidManagement: addFriend(webID)
SolidManagement -> PodProvider: addFriend(friendWebID, userWebID)
Friends -> SolidManagement: loadFriends(webId)
SolidManagement -> PodProvider: loadFriends()
PodProvider -> PodProvider: gets user's pictures and names
PodProvider -> SolidManagement: List of friends
SolidManagement -> Friends: list of friends
Friends -> Friends: shows friends

@enduml
----


=== Share location with friends

Application will allow users to share their locations with their friends. This is achieved by clicking on the share button at a 
location's details and selecting the friend to share with. Then, on the pod, the needed permisions will be given to the friend.

[plantuml,"Share a location with friends",png]
----
@startuml

header LoMap-en2a

title Share a location

database PodProvider
actor User

User -> Map : click on the marker
Map -> Application: setSelectedLocation(location)
Map -> Application: setSelectedView(LocationDetail)
User -> LocationInfo: click share button
LocationInfo -> SolidManagement: loadFriends(webID)
SolidManagement -> PodProvider: loadFriends()
PodProvider -> PodProvider: gets user's pictures and names
PodProvider -> SolidManagement: List of friends
SolidManagement -> LocationInfo: list of friends
User -> LocationInfo: clicks on friend's webId
LocationInfo -> SolidManagement: shareLocation(location, friendWebId)
SolidManagement -> PodProvider: sets the permisions to the friend for the location url

@enduml
----