[[section-design-decisions]]
== Design Decisions

The architectural decisions are completely documented in our ARD section in the Wiki. Due to this, and to avoid redundancy, instead of re-document those decisions here, we will refer to them.

=== Google Maps API
To refer to the documented architectural decision about Google Maps API, click on the link below. +

https://github.com/Arquisoft/lomap_en2a/wiki/ARD---Map-API[Google Maps API]

=== MySQL DataBase
To refer to the documented architectural decision about MySQL DataBase, click on the link below. +

https://github.com/Arquisoft/lomap_en2a/wiki/ARD---Data-Base[MySQL DB]

=== Storing users' ID in DB
==== Problem
For performance reasons, there are some data that should be stored in a centralized way, in other words, using our data base. For now, we have decided to store the user IDs this way.

==== Advantages
Storing this piece of information in this way, we can save the application some time wasting operations, such as having to scan all the users pods in order to retrieve the wanted ID. This ID will be used, for example, in friend requests.

==== Alternatives
We considered the option of storing the user ID in the user pod, but for performance reasons, this was discarded.


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ListOfLocations or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
