[[section-design-decisions]]
== Design Decisions

The architectural decisions are completely documented in our ARD section in the Wiki. Due to this, and to avoid redundancy, instead of re-document those decisions here, we will refer to them.

=== Google Maps API
To refer to the documented architectural decision about Google Maps API, click on the link below. +

https://github.com/Arquisoft/lomap_en2a/wiki/ARD---Map-API[Google Maps API]

=== No DB usage
https://github.com/Arquisoft/lomap_en2a/wiki/ARD-not-Db-usage[No DB usage]
This decision cancels out the following two:
* https://github.com/Arquisoft/lomap_en2a/wiki/ARD---Data-Base[MySQL DB]
* https://github.com/Arquisoft/lomap_en2a/wiki/ARD-Storing-user's-ID-in-DB[Storing users' ID in DB]

=== Design and UI Technologies
==== First UI mockup
https://github.com/Arquisoft/lomap_en2a/wiki/First-mock-up-of-the-application-UI[First mockup]
==== Chakra UI library
https://github.com/Arquisoft/lomap_en2a/wiki/ARD-Use-of-ChakraUI[Use of ChakraUI as REact component library]

=== Solid Pod Structure
https://github.com/Arquisoft/lomap_en2a/wiki/Solid-Pod-Structure[File directory hierarchy in pod]


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
