[[section-design-decisions]]
== Design Decisions


=== Google Maps API
==== Problem
Need to develop a software system capable of provide personalized maps about places and local businesses in any city. In order to do this, a Map API is needed to provide location-aware infographics, mind maps and visualization aids. We need and API which includes geocoding, geolocation, directions and navigation, touch-screen interaction, popups and customizable control objects.

==== Advantages
Some team members have already used the Google Maps API in other projects. This is one of the decisive advantages, since it facilitates the development of the web application. Also it provides a very important series of features that perfectly adapt to the requirements of LoMap:

* Directions: provides a route planner with an estimate of how much time the route takes and can include additional locations the user wants to travel through.
* Places: helps users find points of interest, whether that's a landmark or tourist attraction, a public building such as a school or hospital, or a restaurant or shop. Also provides the possibility of adding reviews or comments to those points of interest.
* Geocoding: allows to accurately mark locations on maps, by converting between street addresses latitude and longitude coordinates. 
* Data layers: lets the user personalize or overlay own data on the map.

==== Alternatives
Apart from Google Maps API, we also considered these other options:
* MapBox API.
* Geopify API.
Both of them were temporarily discarded because of the familiarity of Google Maps. However, we remark temporarily since we plan to implement an adapter pattern that lets us change the used Map API if we consider it necessary.
==== ARD Link
[Google Maps API](https://github.com/Arquisoft/lomap_en2a/wiki/ARD---Map-API)


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
